/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Blog {
  author_id: number;
  content: string | null;
  created_at: Generated<Date | null>;
  id: Generated<number>;
  status: Generated<"draft" | "published" | "unlisted">;
  title: string | null;
  updated_at: Generated<Date | null>;
}

export interface BlogMedia {
  alt_text: string | null;
  blog_id: number;
  deleted_at: Date | null;
  id: Generated<number>;
  media_url: string;
  uploaded_at: Generated<Date | null>;
  uploaded_by: number;
}

export interface Bookmark {
  blogId: number;
  created_at: Generated<Date | null>;
  id: Generated<number>;
  isBookmarked: number;
  updated_at: Generated<Date | null>;
  userId: number;
}

export interface Comment {
  blogId: number;
  comment: string;
  created_at: Generated<Date | null>;
  id: Generated<number>;
  parentComment: number | null;
  updated_at: Generated<Date | null>;
  userId: number;
}

export interface Finance {
  amount: number;
  bill_img: string | null;
  category: "Bills" | "Education" | "Gift" | "Groceries" | "Maintenance" | "Other" | "Public Transit" | "Restaurants" | null;
  date: Generated<Date | null>;
  description: string | null;
  id: Generated<number>;
  transaction_method: "card" | "cash" | "other" | "UPI";
  transaction_type: "credited" | "debited";
  userId: number;
}

export interface Likes {
  blogId: number;
  commentId: number;
  created_at: Generated<Date | null>;
  id: Generated<number>;
  isliked: number;
  updated_at: Generated<Date | null>;
  userId: number;
}

export interface Todo {
  attachment: string | null;
  category: string;
  created_at: Generated<Date | null>;
  description: string;
  due_date: Date | null;
  id: Generated<number>;
  markAsCompleted: number;
  parentTodoId: number | null;
  priorityLevel: "High" | "Low" | "Medium";
  title: string;
  updated_at: Generated<Date | null>;
  userId: number;
}

export interface User {
  created_at: Generated<Date | null>;
  email: string;
  firstname: string;
  id: Generated<number>;
  image_key: string | null;
  lastname: string;
  password: string;
  profilepic: string | null;
  refreshtoken: string | null;
  updated_at: Generated<Date | null>;
  username: string;
}

export interface DB {
  blog: Blog;
  blog_media: BlogMedia;
  bookmark: Bookmark;
  comment: Comment;
  finance: Finance;
  likes: Likes;
  todo: Todo;
  user: User;
}
